version: "3.7"
services:
  jenkins:
    build:
      context: .
      dockerfile: jenkins.dockerfile
    volumes:
      - $PWD/jenkins_home:/var/jenkins_home #Jenkins working directory on HOST : Container
      - $PWD:/app #current directory for app HOST:Container chenge to Git
    ports:
      - 8080:8080 # HOST_port:Container_port
  aws:
    image: organs/awscli
    environment:
      AWS_ACCESS_KEY_ID: "${AWS_ACCESS_KEY_ID}"
      AWS_SECRET_ACCESS_KEY: "${AWS_SECRET_ACCESS_KEY}"
      AWS_REGION: "${AWS_REGION}"
      AWS_DEFAULT_REGION: us-weat-2
    volumes:
      - $PWD:/app
    working_dir: /app
  terraform:
    build:
      dockerfile: terraform.dockerfile
      context: .
    environment:
      AWS_ACCESS_KEY_ID: "${AWS_ACCESS_KEY_ID}"
      AWS_SECRET_ACCESS_KEY: "${AWS_SECRET_ACCESS_KEY}"
      AWS_REGION: "${AWS_REGION}"
      AWS_DEFAULT_REGION: us-weat-2
    volumes:
      - $PWD:/app
    working_dir: /app
  selenium:
    image: selenium/standalone-chrome-debug # debug version include VNC
    ports:
      - 4444:4444 # Selenium port
      - 5901:5900 # VNC ports. The 5900 is default VNC port
  integration-test: # new service
    environment:
      SELENIUM_HOST: selenium
      SELENIUM_PORT: 4444
    volumes: # mount existen volume to container
      - $PWD:/app #current directorin to /app
    build: # build new image
      dockerfile: rspec.dockerfile #spesific dockerfile
      context: . #current context
    command:
      - --pattern # entrypoint option
      - /app/integration/unit/*_spec.rb # entrypoint option test target
  unit-test: # new service
    environment:
      SELENIUM_HOST: selenium
      SELENIUM_PORT: 4444
    volumes: # mount existen volume to container
      - $PWD:/app #current directorin to /app
    build: # build new image
      dockerfile: rspec.dockerfile #spesific dockerfile
      context: . #current context
    command:
      - --pattern # entrypoint option
      - /app/spec/unit/*_spec.rb # entrypoint option test target
  website:
    build:
      context: .
    ports:
      - 80:80
